# Generated by Django 4.0.4 on 2022-05-13 00:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Title of Program')),
                ('tagline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub-title of Program')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('introduction', models.CharField(blank=True, max_length=250, null=True, verbose_name='Program Introduction')),
                ('teaching_mode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teaching Mode')),
                ('academic_history', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, verbose_name='Academic History'), blank=True, null=True, size=None)),
                ('advantages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Program Advantages'), blank=True, null=True, size=None)),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='General Description')),
                ('scholarships', models.CharField(blank=True, max_length=100, null=True, verbose_name='Scholarship Infomation')),
                ('institutions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Institutes'), blank=True, null=True, size=None)),
                ('extra_information', models.JSONField(blank=True, null=True, verbose_name='Add Workplaces')),
            ],
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['name'], name='programs_pr_name_3fd0ea_idx'),
        ),
    ]
