# Generated by Django 4.0.4 on 2022-05-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='academic_history',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Academic History'),
        ),
        migrations.AlterField(
            model_name='program',
            name='advantages',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Program Advantages'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='General Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='extra_information',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='program',
            name='institutions',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Institutes'),
        ),
        migrations.AlterField(
            model_name='program',
            name='scholarships',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Scholarship Infomation'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-title of Program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='teaching_mode',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online'), ('mixed', 'Mixed')], max_length=10, null=True, verbose_name='Teaching Mode'),
        ),
    ]
