# Generated by Django 4.0.4 on 2022-05-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_academic_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='institutions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institutes'),
        ),
    ]
