# Generated by Django 4.0.4 on 2022-05-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='teaching_mode_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teaching Mode Description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='academic_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Academic History'),
        ),
        migrations.AlterField(
            model_name='program',
            name='advantages',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Program Advantages'),
        ),
        migrations.AlterField(
            model_name='program',
            name='introduction',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Program Introduction'),
        ),
    ]
