# Generated by Django 4.0.4 on 2022-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='name of course')),
                ('degree_type', models.CharField(max_length=1, verbose_name='type of degree')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, unique=True, verbose_name='name of school')),
                ('short_name', models.CharField(max_length=10, unique=True, verbose_name='abbreviated name')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
            ],
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['short_name'], name='entities_sc_short_n_a53011_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='entities_co_course__212bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['degree_type'], name='entities_co_degree__89bf6d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name', 'degree_type'], name='entities_co_course__6a5507_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_name', 'degree_type'), name='unique_degree_course'),
        ),
    ]
